#! /usr/bin/Rscript --vanilla
# This is a MacOSX launch script for the DSQDP
# Edit starting working directory here:
starting_dir <- "/Users/sk/Dropbox/Tools/software/R/dsqdp" # EDIT HERE

# switch wd
if (!file.exists(starting_dir)) stop("directory does not exist: ", starting_dir)
setwd(starting_dir)

# info 
message("\nFor this script to work, need to make sure to have GTK+ installed:")
message("	https://gist.github.com/sebkopf/9405675\n")

# start dsqdp
library(dsqdp)
dsqdp.start_from_script()